variable "db_instance_identifier" {}
variable "db_username" {}
variable "db_password" {}
variable "instance_class" {}
variable "allocated_storage" {}
variable "db_subnet_group_name" {}
variable "vpc_security_group_ids" {}
variable "availability_zone" {}
variable "db_name" {}
variable "skip_final_snapshot" {}
